// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storebytes/storebytespb/storebytes.proto

package storebytespb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StoreMessage struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Id                   int32    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Parent               string   `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreMessage) Reset()         { *m = StoreMessage{} }
func (m *StoreMessage) String() string { return proto.CompactTextString(m) }
func (*StoreMessage) ProtoMessage()    {}
func (*StoreMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_426bef090816d491, []int{0}
}

func (m *StoreMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreMessage.Unmarshal(m, b)
}
func (m *StoreMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreMessage.Marshal(b, m, deterministic)
}
func (m *StoreMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreMessage.Merge(m, src)
}
func (m *StoreMessage) XXX_Size() int {
	return xxx_messageInfo_StoreMessage.Size(m)
}
func (m *StoreMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StoreMessage proto.InternalMessageInfo

func (m *StoreMessage) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *StoreMessage) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *StoreMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StoreMessage) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

type StoreRequest struct {
	Msg                  *StoreMessage `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StoreRequest) Reset()         { *m = StoreRequest{} }
func (m *StoreRequest) String() string { return proto.CompactTextString(m) }
func (*StoreRequest) ProtoMessage()    {}
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_426bef090816d491, []int{1}
}

func (m *StoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreRequest.Unmarshal(m, b)
}
func (m *StoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreRequest.Marshal(b, m, deterministic)
}
func (m *StoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreRequest.Merge(m, src)
}
func (m *StoreRequest) XXX_Size() int {
	return xxx_messageInfo_StoreRequest.Size(m)
}
func (m *StoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreRequest proto.InternalMessageInfo

func (m *StoreRequest) GetMsg() *StoreMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

type StoreResponse struct {
	Result               []byte   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreResponse) Reset()         { *m = StoreResponse{} }
func (m *StoreResponse) String() string { return proto.CompactTextString(m) }
func (*StoreResponse) ProtoMessage()    {}
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_426bef090816d491, []int{2}
}

func (m *StoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreResponse.Unmarshal(m, b)
}
func (m *StoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreResponse.Marshal(b, m, deterministic)
}
func (m *StoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreResponse.Merge(m, src)
}
func (m *StoreResponse) XXX_Size() int {
	return xxx_messageInfo_StoreResponse.Size(m)
}
func (m *StoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreResponse proto.InternalMessageInfo

func (m *StoreResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type LongStoreRequest struct {
	Msg                  *StoreMessage `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LongStoreRequest) Reset()         { *m = LongStoreRequest{} }
func (m *LongStoreRequest) String() string { return proto.CompactTextString(m) }
func (*LongStoreRequest) ProtoMessage()    {}
func (*LongStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_426bef090816d491, []int{3}
}

func (m *LongStoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongStoreRequest.Unmarshal(m, b)
}
func (m *LongStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongStoreRequest.Marshal(b, m, deterministic)
}
func (m *LongStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongStoreRequest.Merge(m, src)
}
func (m *LongStoreRequest) XXX_Size() int {
	return xxx_messageInfo_LongStoreRequest.Size(m)
}
func (m *LongStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LongStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LongStoreRequest proto.InternalMessageInfo

func (m *LongStoreRequest) GetMsg() *StoreMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

type LongStoreResponse struct {
	Result               []byte   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongStoreResponse) Reset()         { *m = LongStoreResponse{} }
func (m *LongStoreResponse) String() string { return proto.CompactTextString(m) }
func (*LongStoreResponse) ProtoMessage()    {}
func (*LongStoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_426bef090816d491, []int{4}
}

func (m *LongStoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongStoreResponse.Unmarshal(m, b)
}
func (m *LongStoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongStoreResponse.Marshal(b, m, deterministic)
}
func (m *LongStoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongStoreResponse.Merge(m, src)
}
func (m *LongStoreResponse) XXX_Size() int {
	return xxx_messageInfo_LongStoreResponse.Size(m)
}
func (m *LongStoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LongStoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LongStoreResponse proto.InternalMessageInfo

func (m *LongStoreResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type SendManyTimesRequest struct {
	Msg                  *StoreMessage `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SendManyTimesRequest) Reset()         { *m = SendManyTimesRequest{} }
func (m *SendManyTimesRequest) String() string { return proto.CompactTextString(m) }
func (*SendManyTimesRequest) ProtoMessage()    {}
func (*SendManyTimesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_426bef090816d491, []int{5}
}

func (m *SendManyTimesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendManyTimesRequest.Unmarshal(m, b)
}
func (m *SendManyTimesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendManyTimesRequest.Marshal(b, m, deterministic)
}
func (m *SendManyTimesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendManyTimesRequest.Merge(m, src)
}
func (m *SendManyTimesRequest) XXX_Size() int {
	return xxx_messageInfo_SendManyTimesRequest.Size(m)
}
func (m *SendManyTimesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendManyTimesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendManyTimesRequest proto.InternalMessageInfo

func (m *SendManyTimesRequest) GetMsg() *StoreMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

type SendManyTimesResponse struct {
	Result               []byte   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendManyTimesResponse) Reset()         { *m = SendManyTimesResponse{} }
func (m *SendManyTimesResponse) String() string { return proto.CompactTextString(m) }
func (*SendManyTimesResponse) ProtoMessage()    {}
func (*SendManyTimesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_426bef090816d491, []int{6}
}

func (m *SendManyTimesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendManyTimesResponse.Unmarshal(m, b)
}
func (m *SendManyTimesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendManyTimesResponse.Marshal(b, m, deterministic)
}
func (m *SendManyTimesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendManyTimesResponse.Merge(m, src)
}
func (m *SendManyTimesResponse) XXX_Size() int {
	return xxx_messageInfo_SendManyTimesResponse.Size(m)
}
func (m *SendManyTimesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendManyTimesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendManyTimesResponse proto.InternalMessageInfo

func (m *SendManyTimesResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*StoreMessage)(nil), "example.StoreMessage")
	proto.RegisterType((*StoreRequest)(nil), "example.StoreRequest")
	proto.RegisterType((*StoreResponse)(nil), "example.StoreResponse")
	proto.RegisterType((*LongStoreRequest)(nil), "example.LongStoreRequest")
	proto.RegisterType((*LongStoreResponse)(nil), "example.LongStoreResponse")
	proto.RegisterType((*SendManyTimesRequest)(nil), "example.SendManyTimesRequest")
	proto.RegisterType((*SendManyTimesResponse)(nil), "example.SendManyTimesResponse")
}

func init() {
	proto.RegisterFile("storebytes/storebytespb/storebytes.proto", fileDescriptor_426bef090816d491)
}

var fileDescriptor_426bef090816d491 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xdd, 0xd6, 0xb6, 0x74, 0x6c, 0x8b, 0x2e, 0xb6, 0xc4, 0x80, 0x52, 0x72, 0x69, 0x40,
	0x48, 0xa5, 0x1e, 0x14, 0x3c, 0x08, 0x1e, 0x3c, 0xd9, 0xcb, 0xc6, 0x93, 0xb7, 0xfc, 0x19, 0x42,
	0xa4, 0xd9, 0x8d, 0xd9, 0x8d, 0xd8, 0xef, 0xeb, 0x07, 0x91, 0xc4, 0x4d, 0x1b, 0x43, 0x55, 0xf4,
	0x96, 0x97, 0x37, 0xf3, 0x7e, 0x2f, 0x9b, 0x05, 0x5b, 0x2a, 0x91, 0xa1, 0xbf, 0x56, 0x28, 0xe7,
	0xdb, 0xc7, 0xd4, 0xaf, 0x09, 0x27, 0xcd, 0x84, 0x12, 0xb4, 0x87, 0x6f, 0x5e, 0x92, 0xae, 0xd0,
	0x7a, 0x86, 0x81, 0x5b, 0x98, 0x4b, 0x94, 0xd2, 0x8b, 0x90, 0x1a, 0xd0, 0x0b, 0x04, 0x57, 0xc8,
	0x95, 0x41, 0xa6, 0xc4, 0x1e, 0xb0, 0x4a, 0x16, 0x8e, 0x17, 0x04, 0x22, 0xe7, 0xca, 0x68, 0x4d,
	0x89, 0xdd, 0x67, 0x95, 0xa4, 0x23, 0x68, 0xc5, 0xa1, 0xd1, 0x9e, 0x12, 0xbb, 0xc3, 0x5a, 0x71,
	0x48, 0x27, 0xd0, 0x4d, 0xbd, 0xac, 0x88, 0xd8, 0x2f, 0x07, 0xb5, 0xb2, 0xae, 0x34, 0x8b, 0xe1,
	0x4b, 0x8e, 0x52, 0xd1, 0x19, 0xb4, 0x13, 0x19, 0x95, 0x9c, 0x83, 0xc5, 0xd8, 0xd1, 0x95, 0x9c,
	0x7a, 0x1f, 0x56, 0x4c, 0x58, 0x33, 0x18, 0xea, 0x45, 0x99, 0x0a, 0x2e, 0xb1, 0x20, 0x64, 0x28,
	0xf3, 0x55, 0x55, 0x52, 0x2b, 0xeb, 0x06, 0x0e, 0x1f, 0x04, 0x8f, 0xfe, 0x47, 0x39, 0x87, 0xa3,
	0xda, 0xf2, 0x2f, 0xa4, 0x5b, 0x38, 0x76, 0x91, 0x87, 0x4b, 0x8f, 0xaf, 0x1f, 0xe3, 0x04, 0xe5,
	0x9f, 0x69, 0x73, 0x18, 0x37, 0x02, 0x7e, 0x26, 0x2e, 0xde, 0x89, 0x3e, 0x3e, 0x17, 0xb3, 0xd7,
	0x38, 0x40, 0x7a, 0x0d, 0x9d, 0x52, 0xd3, 0x06, 0x46, 0x57, 0x31, 0x27, 0xcd, 0xd7, 0x9f, 0x00,
	0x6b, 0x8f, 0x32, 0x18, 0x7e, 0x61, 0xd3, 0xd3, 0xed, 0xe8, 0x8e, 0x8f, 0x32, 0xcf, 0xbe, 0xb3,
	0xab, 0xc4, 0x0b, 0x42, 0xef, 0xa1, 0xbf, 0x39, 0x3d, 0x7a, 0xb2, 0x59, 0x68, 0xfe, 0x0e, 0xd3,
	0xdc, 0x65, 0x55, 0x39, 0x36, 0xb9, 0x1b, 0x3d, 0x0d, 0xea, 0x57, 0xd7, 0xef, 0x96, 0x17, 0xf6,
	0xf2, 0x23, 0x00, 0x00, 0xff, 0xff, 0x01, 0x4f, 0xec, 0x21, 0xdc, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreServiceClient interface {
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	// server streaming
	SendManyTimes(ctx context.Context, in *SendManyTimesRequest, opts ...grpc.CallOption) (StoreService_SendManyTimesClient, error)
	//client streaming
	LongStore(ctx context.Context, opts ...grpc.CallOption) (StoreService_LongStoreClient, error)
}

type storeServiceClient struct {
	cc *grpc.ClientConn
}

func NewStoreServiceClient(cc *grpc.ClientConn) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, "/example.StoreService/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) SendManyTimes(ctx context.Context, in *SendManyTimesRequest, opts ...grpc.CallOption) (StoreService_SendManyTimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StoreService_serviceDesc.Streams[0], "/example.StoreService/SendManyTimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeServiceSendManyTimesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StoreService_SendManyTimesClient interface {
	Recv() (*SendManyTimesResponse, error)
	grpc.ClientStream
}

type storeServiceSendManyTimesClient struct {
	grpc.ClientStream
}

func (x *storeServiceSendManyTimesClient) Recv() (*SendManyTimesResponse, error) {
	m := new(SendManyTimesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storeServiceClient) LongStore(ctx context.Context, opts ...grpc.CallOption) (StoreService_LongStoreClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StoreService_serviceDesc.Streams[1], "/example.StoreService/LongStore", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeServiceLongStoreClient{stream}
	return x, nil
}

type StoreService_LongStoreClient interface {
	Send(*LongStoreRequest) error
	CloseAndRecv() (*LongStoreResponse, error)
	grpc.ClientStream
}

type storeServiceLongStoreClient struct {
	grpc.ClientStream
}

func (x *storeServiceLongStoreClient) Send(m *LongStoreRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storeServiceLongStoreClient) CloseAndRecv() (*LongStoreResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(LongStoreResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StoreServiceServer is the server API for StoreService service.
type StoreServiceServer interface {
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	// server streaming
	SendManyTimes(*SendManyTimesRequest, StoreService_SendManyTimesServer) error
	//client streaming
	LongStore(StoreService_LongStoreServer) error
}

// UnimplementedStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStoreServiceServer struct {
}

func (*UnimplementedStoreServiceServer) Store(ctx context.Context, req *StoreRequest) (*StoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (*UnimplementedStoreServiceServer) SendManyTimes(req *SendManyTimesRequest, srv StoreService_SendManyTimesServer) error {
	return status.Errorf(codes.Unimplemented, "method SendManyTimes not implemented")
}
func (*UnimplementedStoreServiceServer) LongStore(srv StoreService_LongStoreServer) error {
	return status.Errorf(codes.Unimplemented, "method LongStore not implemented")
}

func RegisterStoreServiceServer(s *grpc.Server, srv StoreServiceServer) {
	s.RegisterService(&_StoreService_serviceDesc, srv)
}

func _StoreService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.StoreService/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_SendManyTimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendManyTimesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreServiceServer).SendManyTimes(m, &storeServiceSendManyTimesServer{stream})
}

type StoreService_SendManyTimesServer interface {
	Send(*SendManyTimesResponse) error
	grpc.ServerStream
}

type storeServiceSendManyTimesServer struct {
	grpc.ServerStream
}

func (x *storeServiceSendManyTimesServer) Send(m *SendManyTimesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StoreService_LongStore_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StoreServiceServer).LongStore(&storeServiceLongStoreServer{stream})
}

type StoreService_LongStoreServer interface {
	SendAndClose(*LongStoreResponse) error
	Recv() (*LongStoreRequest, error)
	grpc.ServerStream
}

type storeServiceLongStoreServer struct {
	grpc.ServerStream
}

func (x *storeServiceLongStoreServer) SendAndClose(m *LongStoreResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storeServiceLongStoreServer) Recv() (*LongStoreRequest, error) {
	m := new(LongStoreRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _StoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _StoreService_Store_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendManyTimes",
			Handler:       _StoreService_SendManyTimes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LongStore",
			Handler:       _StoreService_LongStore_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "storebytes/storebytespb/storebytes.proto",
}
